#!/usr/bin/env python3

import json
import sys

if sys.version_info < (3, 6):
    raise Exception("Need at least Python 3.6 for this tool")
    # https://docs.python.org/3/whatsnew/3.6.html
    # > json.load() and json.loads() now support binary input.

from html.parser import HTMLParser
from urllib.request import urlopen

DEFAULT_BASE_URL = "https://go.dev/dl/"


def main():
    for self_link in _fetch_links():
        print(self_link)
    return 0


class GoDevDLParser(HTMLParser):
    def __init__(self, base_url=DEFAULT_BASE_URL, *args, **kwargs):
        super(GoDevDLParser, self).__init__(*args, **kwargs)

        self.urls = []
        self.base_url = base_url

    def handle_starttag(self, tag, attrs):
        if tag != "a":
            return

        attr_dict = dict(attrs)
        if "href" not in attr_dict or attr_dict.get("class") != "download":
            return

        self.urls.append(
            "/".join([self.base_url.rstrip("/dl/"), attr_dict["href"].lstrip("/")])
        )


def _fetch_links(base_url=DEFAULT_BASE_URL):
    parser = GoDevDLParser()
    parser.feed(urlopen(base_url).read().decode("utf-8"))

    return parser.urls


if __name__ == "__main__":
    sys.exit(main())
